# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: links.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='links.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0blinks.proto\"-\n\x04Link\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"?\n\x0eReccomendation\x12\x11\n\tinputTags\x18\x01 \x03(\t\x12\x1a\n\x0boutputLinks\x18\x02 \x03(\x0b\x32\x05.Linkb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Link.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='Link.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Link.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=60,
)


_RECCOMENDATION = _descriptor.Descriptor(
  name='Reccomendation',
  full_name='Reccomendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputTags', full_name='Reccomendation.inputTags', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputLinks', full_name='Reccomendation.outputLinks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=125,
)

_RECCOMENDATION.fields_by_name['outputLinks'].message_type = _LINK
DESCRIPTOR.message_types_by_name['Link'] = _LINK
DESCRIPTOR.message_types_by_name['Reccomendation'] = _RECCOMENDATION

Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
  DESCRIPTOR = _LINK,
  __module__ = 'links_pb2'
  # @@protoc_insertion_point(class_scope:Link)
  ))
_sym_db.RegisterMessage(Link)

Reccomendation = _reflection.GeneratedProtocolMessageType('Reccomendation', (_message.Message,), dict(
  DESCRIPTOR = _RECCOMENDATION,
  __module__ = 'links_pb2'
  # @@protoc_insertion_point(class_scope:Reccomendation)
  ))
_sym_db.RegisterMessage(Reccomendation)


# @@protoc_insertion_point(module_scope)
